const products = [
  {
    id: 1,
    category: "revelacoes",
    title: "Revelação De fotos",
    content: `Imortalize seus momentos favoritos em uma foto 10x15! Escolha entre o acabamento brilhante para um brilho vibrante ou o acabamento fosco para uma elegância sutil. Capture memórias que durarão para sempre.`,
    price: "Consulte",
    img: "/foto-card.jpeg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de `,
  },
  {
    id: 2,
    category: "revelacoes",
    title: "Banners",
    content: `Imortalize seus momentos favoritos em uma foto 10x15! Escolha entre o acabamento brilhante para um brilho vibrante ou o acabamento fosco para uma elegância sutil. Capture memórias que durarão para sempre.`,
    price: "Consulte",
    img: "/catalogo_fotos/banner.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de saber mais sobre`,
  },
  {
    id: 3,
    category: "albuns",
    title: "Álbum",
    content: ``,
    price: "R$ 10,90",
    img: "/catalogo_fotos/album.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 4,
    category: "Almofadas",
    title: "Almofada Branca",
    content: ``,
    price: "R$ 39,90",
    img: "/catalogo_fotos/almofada_branca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 5,
    category: "Almofadas",
    title: "Almofada Coração",
    content: ``,
    price: "R$ 29,90",
    img: "/catalogo_fotos/almofada_coracao.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 6,
    category: "Almofadas",
    title: "Almofada com Lantejoula",
    content: ``,
    price: "R$ 35,90",
    img: "/catalogo_fotos/almofada_lantejoula.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 7,
    category: "Almofadas",
    title: "Almofada Preta",
    content: ``,
    price: "R$ 35,90",
    img: "/catalogo_fotos/almofada_preta.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 8,
    category: "Azulejo",
    title: "Azulejo",
    content: ``,
    price: "R$ 35,90",
    img: "/catalogo_fotos/azulejo.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 9,
    category: "Roupas",
    title: "Body de Bebê",
    content: ``,
    price: "R$ 29,90",
    img: "/catalogo_fotos/body_bebe.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 10,
    category: "Calendários",
    title: "Calendário de Mesa",
    content: ``,
    price: "R$ 29,90",
    img: "/catalogo_fotos/calendario_mesa.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 11,
    category: "Calendários",
    title: "Calendário",
    content: ``,
    price: "Consulte",
    img: "/catalogo_fotos/calendario.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 12,
    category: "Câmeras",
    title: "Câmera Instax Mini",
    content: ``,
    price: "R$ 479,90",
    img: "/catalogo_fotos/camera_instax.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 13,
    category: "Roupas",
    title: "Camiseta Branca",
    content: ``,
    price: "R$ 39,90",
    img: "/catalogo_fotos/camiseta_branca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 14,
    category: "Roupas",
    title: "Camiseta Preta",
    content: ``,
    price: "R$ 49,90",
    img: "/catalogo_fotos/camiseta_preta.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 15,
    category: "Canecas",
    title: "Caneca Branca",
    content: ``,
    price: "R$ 45,00",
    img: "/catalogo_fotos/caneca_branca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 16,
    category: "Canecas",
    title: "Caneca Colorida",
    content: ``,
    price: "R$ 55,00",
    img: "/catalogo_fotos/caneca_color.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 17,
    category: "Canecas",
    title: "Caneca Preta com Faixa Branca",
    content: ``,
    price: "R$ 55,00",
    img: "/catalogo_fotos/caneca_faixabranca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 18,
    category: "Canecas",
    title: "Caneca Mágica",
    content: ``,
    price: "R$ 55,00",
    img: "/catalogo_fotos/caneca_magica.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 19,
    category: "Canecas",
    title: "Caneca Mágica com Colher",
    content: ``,
    price: "R$ 55,00",
    img: "/catalogo_fotos/caneca_magica_colher.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 20,
    category: "Canecas",
    title: "Caneca de Polímero",
    content: ``,
    price: "R$ 25,00",
    img: "/catalogo_fotos/caneca_polimero.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 21,
    category: "Canecas",
    title: "Caneca Preta",
    content: ``,
    price: "R$ 45,00",
    img: "/catalogo_fotos/caneca_preta.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 22,
    category: "Chaveiros",
    title: "Chaveiro 3x4",
    content: ``,
    price: "R$ 10,00",
    img: "/catalogo_fotos/chaveiro_3x4.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 23,
    category: "Chaveiros",
    title: "Chaveiro de Almofadinha",
    content: ``,
    price: "R$ 8,00",
    img: "/catalogo_fotos/chaveiro_almofadinha.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 24,
    category: "Chaveiros",
    title: "Chaveiro de Metal Coração",
    content: ``,
    price: "R$ 27,00",
    img: "/catalogo_fotos/chaveiro_metal_coracao.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 25,
    category: "Chaveiros",
    title: "Chaveiro Redondo",
    content: ``,
    price: "R$ 10,00",
    img: "/catalogo_fotos/chaveiro_redondo.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 26,
    category: "Copos",
    title: "Copo Stanley",
    content: ``,
    price: "R$ 36,00",
    img: "/catalogo_fotos/copo_stanley.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
];

export default products;
