const products = [
  {
    id: 1,
    category: "revelacoes",
    title: "Revelação De fotos",
    content: `Imortalize seus momentos favoritos em uma foto 10x15! Escolha entre o acabamento brilhante para um brilho vibrante ou o acabamento fosco para uma elegância sutil. Capture memórias que durarão para sempre.`,
    price: "Consulte",
    img: "/foto-card.jpeg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de `,
  },
  {
    id: 2,
    category: "revelacoes",
    title: "Banners",
    content: `Imortalize seus momentos favoritos em uma foto 10x15! Escolha entre o acabamento brilhante para um brilho vibrante ou o acabamento fosco para uma elegância sutil. Capture memórias que durarão para sempre.`,
    price: "Consulte",
    img: "/catalogo_fotos/banner.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de saber mais sobre`,
  },
  {
    id: 3,
    category: "albuns",
    title: "Álbum",
    content: ``,
    price: "R$ 10,90",
    img: "/catalogo_fotos/album.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 4,
    category: "Almofadas",
    title: "Almofada Branca",
    content: ``,
    price: "R$ 39,90",
    img: "/catalogo_fotos/almofada_branca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 5,
    category: "Almofadas",
    title: "Almofada Coração",
    content: ``,
    price: "R$ 29,90",
    img: "/catalogo_fotos/almofada_coracao.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 6,
    category: "Almofadas",
    title: "Almofada com Lantejoula",
    content: ``,
    price: "R$ 35,90",
    img: "/catalogo_fotos/almofada_lantejoula.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 7,
    category: "Almofadas",
    title: "Almofada Preta",
    content: ``,
    price: "R$ 35,90",
    img: "/catalogo_fotos/almofada_preta.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 8,
    category: "Azulejo",
    title: "Azulejo",
    content: ``,
    price: "R$ 35,90",
    img: "/catalogo_fotos/azulejo.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 9,
    category: "Roupas",
    title: "Body de Bebê",
    content: ``,
    price: "R$ 29,90",
    img: "/catalogo_fotos/body_bebe.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 10,
    category: "Calendários",
    title: "Calendário de Mesa",
    content: ``,
    price: "R$ 29,90",
    img: "/catalogo_fotos/calendario_mesa.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 11,
    category: "Calendários",
    title: "Calendário",
    content: ``,
    price: "Consulte",
    img: "/catalogo_fotos/calendario.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 12,
    category: "Câmeras",
    title: "Câmera Instax Mini",
    content: ``,
    price: "R$ 479,90",
    img: "/catalogo_fotos/camera_instax.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 13,
    category: "Roupas",
    title: "Camiseta Branca",
    content: ``,
    price: "R$ 39,90",
    img: "/catalogo_fotos/camiseta_branca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 14,
    category: "Roupas",
    title: "Camiseta Preta",
    content: ``,
    price: "R$ 49,90",
    img: "/catalogo_fotos/camiseta_preta.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 15,
    category: "Canecas",
    title: "Caneca Branca",
    content: ``,
    price: "R$ 45,00",
    img: "/catalogo_fotos/caneca_branca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 16,
    category: "Canecas",
    title: "Caneca Colorida",
    content: ``,
    price: "R$ 55,00",
    img: "/catalogo_fotos/caneca_color.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 17,
    category: "Canecas",
    title: "Caneca Preta com Faixa Branca",
    content: ``,
    price: "R$ 55,00",
    img: "/catalogo_fotos/caneca_faixabranca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 18,
    category: "Canecas",
    title: "Caneca Mágica",
    content: ``,
    price: "R$ 55,00",
    img: "/catalogo_fotos/caneca_magica.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 19,
    category: "Canecas",
    title: "Caneca Mágica com Colher",
    content: ``,
    price: "R$ 55,00",
    img: "/catalogo_fotos/caneca_magica_colher.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 20,
    category: "Canecas",
    title: "Caneca de Polímero",
    content: ``,
    price: "R$ 25,00",
    img: "/catalogo_fotos/caneca_polimero.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 21,
    category: "Canecas",
    title: "Caneca Preta",
    content: ``,
    price: "R$ 45,00",
    img: "/catalogo_fotos/caneca_preta.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 22,
    category: "Chaveiros",
    title: "Chaveiro 3x4",
    content: ``,
    price: "R$ 10,00",
    img: "/catalogo_fotos/chaveiro_3x4.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 23,
    category: "Chaveiros",
    title: "Chaveiro de Almofadinha",
    content: ``,
    price: "R$ 8,00",
    img: "/catalogo_fotos/chaveiro_almofadinha.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 24,
    category: "Chaveiros",
    title: "Chaveiro de Metal Coração",
    content: ``,
    price: "R$ 27,00",
    img: "/catalogo_fotos/chaveiro_metal_coracao.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 25,
    category: "Chaveiros",
    title: "Chaveiro Redondo",
    content: ``,
    price: "R$ 10,00",
    img: "/catalogo_fotos/chaveiro_redondo.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 26,
    category: "Copos",
    title: "Copo Stanley",
    content: ``,
    price: "R$ 36,00",
    img: "/catalogo_fotos/copo_stanley.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 27,
    category: "Copos",
    title: "Caneca de Chop Degradê",
    content: ``,
    price: "R$ 36,00",
    img: "/catalogo_fotos/chop_degrade.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 28,
    category: "Copos",
    title: "Caneca de Chop Jateada",
    content: ``,
    price: "R$ 36,00",
    img: "/catalogo_fotos/chop_jateada.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 29,
    category: "Copos",
    title: "Caneca de Chop Transparente",
    content: ``,
    price: "R$ 36,00",
    img: "/catalogo_fotos/chop_jateada.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 30,
    category: "Copos",
    title: "Copo Comprido",
    content: ``,
    price: "R$ 36,00",
    img: "/catalogo_fotos/copo_comprido.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 31,
    category: "Filme",
    title: "Filme Instax 10 Unidades",
    content: ``,
    price: "R$ 109,00",
    img: "/catalogo_fotos/filme_instax_10.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 32,
    category: "Filme",
    title: "Filme Instax 20 Unidades",
    content: ``,
    price: "R$ 119,00",
    img: "/catalogo_fotos/filme_instax_20.jpeg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 33,
    category: "Fotos",
    title: "Fotos 3x4 - 6 Unidades",
    content: ``,
    price: "R$ 25,00",
    img: "/catalogo_fotos/foto_3x4.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 34,
    category: "Fotos",
    title: "Fotolivro",
    content: ``,
    price: "R$ 310,00",
    img: "/catalogo_fotos/fotolivro.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 35,
    category: "Garrafa",
    title: "Garrafa Biquinho Prata",
    content: ``,
    price: "R$ 30,00",
    img: "/catalogo_fotos/garrafa_biquinho_prata.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 36,
    category: "Garrafa",
    title: "Garrafa De Rosquear Branca",
    content: ``,
    price: "R$ 30,00",
    img: "/catalogo_fotos/garrafa_rosca_branca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 37,
    category: "Garrafa",
    title: "Garrafa De Rosquear Branca",
    content: ``,
    price: "R$ 30,00",
    img: "/catalogo_fotos/garrafa_rosca_branca_2.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 38,
    category: "Garrafa",
    title: "Garrafa De Rosquear Inox",
    content: ``,
    price: "R$ 30,00",
    img: "/catalogo_fotos/garrafa_rosca_inox.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 39,
    category: "Garrafa",
    title: "Garrafa Squeeze Branca",
    content: ``,
    price: "R$ 30,00",
    img: "/catalogo_fotos/garrafa_squeeze_branca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 40,
    category: "Garrafa",
    title: "Garrafa Squeeze Branca - Novo Modelo!",
    content: ``,
    price: "R$ 30,00",
    img: "/catalogo_fotos/squeeze_nova_branca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 41,
    category: "Instax",
    title: "Kit Instax Mini 12",
    content: ``,
    price: "R$ 579,00",
    img: "/catalogo_fotos/kit_instax.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 42,
    category: "Mousepads",
    title: "Mousepad de Coração",
    content: ``,
    price: "R$ 29,00",
    img: "/catalogo_fotos/mousepad_coracao.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 43,
    category: "Mousepads",
    title: "Mousepad Com Apoio Para Descanso",
    content: ``,
    price: "R$ 29,00",
    img: "/catalogo_fotos/mousepad_descanso.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 44,
    category: "Mousepads",
    title: "Mousepad Retangular",
    content: ``,
    price: "R$ 29,00",
    img: "/catalogo_fotos/mousepad_retangular.png",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 45,
    category: "Quadros",
    title: "Quadro 10x15",
    content: ``,
    price: "R$ 11,90",
    img: "/catalogo_fotos/quadro_10x15.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 46,
    category: "Quadros",
    title: "Quadro 10x15 Com Borda Detalhada",
    content: ``,
    price: "R$ 16,90",
    img: "/catalogo_fotos/quadro_10x15_dif.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 47,
    category: "Quadros",
    title: "Quadro 13x18",
    content: ``,
    price: "R$ 15,90",
    img: "/catalogo_fotos/quadro_13x18.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 48,
    category: "Quadros",
    title: "Quadro 13x18 Com Borda Detalhada",
    content: ``,
    price: "R$ 18,90",
    img: "/catalogo_fotos/quadro_13x18_dif.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 49,
    category: "Quadros",
    title: "Quadro 15x21",
    content: ``,
    price: "R$ 21,90",
    img: "/catalogo_fotos/quadro_15x21.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 50,
    category: "Quadros",
    title: "Quadro 15x21 Com Borda Detalhada",
    content: ``,
    price: "R$ 25,90",
    img: "/catalogo_fotos/quadro_15x21_dif.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 51,
    category: "Quadros",
    title: "Quadro 20x25",
    content: ``,
    price: "R$ 25,90",
    img: "/catalogo_fotos/quadro_20x25.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 52,
    category: "Quadros",
    title: "Quadro 20x30",
    content: ``,
    price: "R$ 25,90",
    img: "/catalogo_fotos/quadro_20x30.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 53,
    category: "Quebra Cabeça",
    title: "Quebra cabeça",
    content: ``,
    price: "R$ 25,90",
    img: "/catalogo_fotos/quebra_cabeca.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
  {
    id: 54,
    category: "Taça",
    title: "Taça Transparente",
    content: ``,
    price: "R$ 25,90",
    img: "/catalogo_fotos/taca_transparente.jpg",
    link: `https://wa.me/+5511953147703/?text=Olá, gostaria de fazer um pedido de`,
  },
];

export default products;
